---
- stat: path={{ app_path }}/vendor
  register: vendordir

- name: make sure applicable folders are writable
  file:
    path={{ item }}
    state=directory
    mode=0777
    recurse=yes
  with_items:
    - "{{ app_path }}/app/cache"
    - "{{ app_path }}/app/logs"
    - "{{ app_path }}/web/uploads"

- name: composer install
  when: not vendordir.stat.exists
  composer: command=install working_dir={{ app_path }} no_dev={{ composer_no_dev }}
  register: composer_install

- stat: path={{ app_path }}/app/config/parameters.yml
  register: parameters_file

- name: copy parameters file
  when: not parameters_file.stat.exists
  command: cp {{ app_path }}/app/config/parameters.yml{.dist,}
