---
- name: install trusted php gpg
  get_url: url="https://packages.sury.org/php/apt.gpg" dest="/etc/apt/trusted.gpg.d/php.gpg"

- name: add php7.1 repo
  apt_repository: repo="{{ item }}"
  with_items:
    - deb https://packages.sury.org/php/ {{ debian_version }} main
  tags: php7.1

- name: apt update
  sudo: true
  apt: update_cache=yes cache_valid_time=7200

- name: install php7.1-cli
  apt: pkg=php7.1-cli state=latest

# You may need to symlink 'ln -s /etc/php/7.1/mods-available /etc/php/mods-available'
# for some modules to install properly
- name: install php7 libraries
  apt: pkg={{item}} state=latest
  with_items:
    - php7.1-mcrypt
    - php7.1-curl
    - php7.1-mysql
    - php7.1-readline
    - php7.1-json
    - php7.1-xml
    - php7.1-opcache
    - php7.1-gd
    - php7.1-redis
    - php7.1-mbstring
    - php7.1-zip
    - php7.1-phpdbg
    # - php7.1-xdebug
    # - php7.1-memcache
    # - php7.1-memcached

- name: install composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer

- file: path=~/.composer state=directory mode=0755

- name: add github auth token
  template:
    src: composer-auth.json
    dest: "~/.composer/auth.json"
    backup: no

- name: install php7-cli config file
  template: backup=no
            dest=/etc/php/7.1/cli/php.ini
            src=php-cli.ini
            owner=root
            group=root
            mode=0644

- name: install php7.1-fpm
  apt: pkg=php7.1-fpm state=latest

- name: copy php7.1-fpm php.ini
  template: backup=no
            dest=/etc/php/7.1/fpm/php.ini
            src=php-fpm.ini
            owner=root
            group=root
            mode=0644
  notify:
    - restart php-fpm

- name: copy php7.1-fpm config
  template: backup=no
            dest=/etc/php/7.1/fpm/php-fpm.conf
            src=php-fpm.conf
            owner=root
            group=root
            mode=0644
  notify:
    - restart php-fpm

- name: copy php7.1-fpm www.conf
  template: backup=no
            dest=/etc/php/7.1/fpm/pool.d/www.conf
            src=php-fpm-www.conf
            owner=root
            group=root
            mode=0644
  notify:
    - restart php-fpm

- stat: path=/etc/nginx
  register: nginx_path

- name: copy php-fastcgi.conf to /etc/nginx
  template: backup=no
      dest=/etc/nginx/php-fastcgi.conf
            src=php-fastcgi.conf.j2
            owner=root
            group=root
            mode=0644
  when: nginx_path.stat.exists
  notify:
    - restart nginx
